version: '3.8'

services:
  ctfd:
    image: ctfd/ctfd:3.7.5
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db/${DB_DATABASE}
      - REDIS_URL=redis://cache:6379
      - WORKERS=2
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./themes:/opt/CTFd/CTFd/themes:ro
      - ./plugins:/opt/CTFd/CTFd/plugins:ro
    depends_on:
      - db
      - cache
    networks:
      default:
      internal:

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal:

  cache:
    image: redis:7-alpine
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      internal:

  # --- SIGNAL-05 PWN CHALLENGE SERVICE ---
  challenge-signal05:
    build:
      context: ./challenges/signal-05-pwn
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9005:9005"
    networks:
      - default
    # Kaynak kısıtlaması (DDoS ve DoS engeli)
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

networks:
  default:
  internal:
    internal: true

  