services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=station_3487_super_secret_key_prod_x92
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd_db_pass_3487@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - db
      - cache
    networks:
      default:
      internal:

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_secure_pass_3487
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd_db_pass_3487
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal:

  cache:
    image: redis:7-alpine
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      internal:

networks:
  default:
  internal:
    internal: true